### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by postmodern** [steakknife/resolv-idn#3]
There is ambigious syntax in the example which causes it to return `[]`

    Resolv::DNS.open do |dns| puts dns.getresources('一流大學.中国', Resolv::DNS::Resource::IN::MX).inspect end
    # => []

If we add a `;`, the example raises a UTF-8 error:

    Resolv::DNS.open do |dns|; puts dns.getresources('一流大學.中国', Resolv::DNS::Resource::IN::MX).inspect; end
    Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:753:in `[]='
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:753:in `sender'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:518:in `block in each_resource'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:1063:in `block (3 levels) in resolv'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:1061:in `each'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:1061:in `block (2 levels) in resolv'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:1060:in `each'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:1060:in `block in resolv'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:1058:in `each'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:1058:in `resolv'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:513:in `each_resource'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:500:in `getresources'
    (ripl):6:in `block in <main>'
    /home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/resolv.rb:302:in `open'

**Comment by steakknife** [comment]
Easy fix.  In transit, Will do when in front of a computer.  

—
