### ISSUE TITLE
Hook getaddress/getaddresses?

### ISSUE THREAD

**Issue by postmodern** [steakknife/resolv-idn#5]
Isresolv-idn supposed to allow `Resolv.getaddress` or `Resolv.getaddresses` to query unicode domain names, or am I supposed to explicitly create a `Resolv::DNS::Name` and call `#to_ascii!`?

**Comment by steakknife** [comment]
Shouldn't have to do anything unless the format needs to be always one or the other.  It could use a global setting to force the defaults.

—

**Comment by postmodern** [comment]
You could check `String#ascii_only?`, although not sure when that method was introduced.

**Comment by steakknife** [comment]
A little later this evening, I'll look at the default behavior and evaluate adding a class attribute.
